name: Build Ports

on:
  push:
    branches:
      - master
    paths:
      - 'docker-entrypoint.py'
      - 'esp32/*'
      - 'esp8266/*'
      - 'unix/*'
      - '.github/workflows/build.yml'
      - 'actions/**/*'
  pull_request:
    paths:
      - 'docker-entrypoint.py'
      - 'esp32/*'
      - 'esp8266/*'
      - 'unix/*'
      - '.github/workflows/build.yml'
      - 'actions/**/*'

jobs:
  build_micropython:
    name: Build MicroPython
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [micropython]
        repo: ['https://github.com/micropython/micropython.git']
        branch: [v1.12, v1.11]
        port: [esp32, esp8266, unix]
        include:
          - branch: v1.12
            idf: 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df
          - branch: v1.11
            idf: 5c88c5996dbde6208e3bec05abc21ff6cd822d26
          

    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@2.0.0

      - name: Build ${{ matrix.name }} ${{ matrix.port }} ${{ matrix.branch }}
        id: micropy-build
        uses: ./actions/build-micropython
        with:
          name: ${{ matrix.name }}
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}
          idf: ${{ matrix.idf }}
          port: ${{ matrix.port }}
          path: ./${{ matrix.port }}
          docker_registry: docker.pkg.github.com
          docker_username: ${{ secrets.REGISTRY_USERNAME }}
          docker_password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Upload Binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.micropy-build.outputs.binaries }}
          path: ./${{ steps.micropy-build.outputs.binaries }}

  build_pycopy:
    name: Build Pycopy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [pycopy]
        repo: ['https://github.com/pfalcon/pycopy.git']
        branch: [v2.11.0.10, v2.11.0.15]
        port: [esp32, esp8266, unix]
        include:
          - branch: v2.11.0.10
            idf: 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df
          - branch: v2.11.0.15
            idf: 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df
          - branch: v2.11.0.15
            idf: 310beae373446ceb9a4ad9b36b5428d7fdf2705f

    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@2.0.0

      - name: Build ${{ matrix.name }} ${{ matrix.port }} ${{ matrix.branch }}
        id: micropy-build
        uses: ./actions/build-micropython
        with:
          name: ${{ matrix.name }}
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}
          idf: ${{ matrix.idf }}
          port: ${{ matrix.port }}
          path: ./${{ matrix.port }}
          docker_registry: docker.pkg.github.com
          docker_username: ${{ secrets.REGISTRY_USERNAME }}
          docker_password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Upload Binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.micropy-build.outputs.binaries }}
          path: ./${{ steps.micropy-build.outputs.binaries }}

  build_pycom:
    name: Build Pycom
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
          [
            pycom-wipy,
            pycom-lopy,
            pycom-sipy,
            pycom-gpy,
            pycom-fipy,
            pycom-lopy4,
          ]
        repo: ['https://github.com/pycom/pycom-micropython-sigfox.git']
        branch: [v1.18.3, v1.20.1.r1]
        idf: [master]
        port_root: ['.']
        idf_repo: ['https://github.com/pycom/pycom-esp-idf.git']
        include:
          - name: pycom-wipy
            board: WIPY
          - name: pycom-lopy
            board: LOPY
          - name: pycom-sipy
            board: SIPY
          - name: pycom-gpy
            board: GPY
          - name: pycom-fipy
            board: FIPY
          - name: pycom-lopy4
            board: LOPY4
    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@2.0.0

      - name: Build ${{ matrix.name }} ESP32 ${{ matrix.branch }}
        id: micropy-build
        uses: ./actions/build-micropython
        with:
          name: ${{ matrix.name }}
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}
          idf: ${{ matrix.idf }}
          idf_repo: ${{ matrix.idf_repo }}
          board: ${{ matrix.board}}
          port_root: ${{ matrix.port_root }}
          path: ./esp32
          docker_registry: docker.pkg.github.com
          docker_username: ${{ secrets.REGISTRY_USERNAME }}
          docker_password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Upload Binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.micropy-build.outputs.binaries }}
          path: ./${{ steps.micropy-build.outputs.binaries }}
