name: Build MicroPython

on:
  push:
    branches:
      - master

jobs:
  esp32:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - name: micropython
            repo: micropython/micropython
            branch: v1.11
            idf: 5c88c5996dbde6208e3bec05abc21ff6cd822d26
          - name: pycopy
            repo: pfalcon/pycopy
            branch: v2.11.0.10
            idf: 6ccb4cf5b7d1fdddb8c2492f9cbc926abaf230df
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build ${{ matrix.args.name }} ESP32
        run: docker build --build-arg REPO="https://github.com/${{ matrix.args.repo }}.git" --build-arg BRANCH="${{ matrix.args.branch }}" --build-arg IDF="${{ matrix.args.idf }}" --tag docker.pkg.github.com/bradenm/micropy-build/${{ matrix.args.name }}:${{ matrix.args.branch }}-esp32 ./esp32

      - name: Publish Image
        run: docker push docker.pkg.github.com/bradenm/micropy-build/${{ matrix.args.name }}:${{ matrix.args.branch }}-esp32

  esp8266:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: textbook/git-checkout-submodule-action@2.0.0
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build ESP8266 v1.11
        run: docker build --build-arg BRANCH="v1.11" --tag docker.pkg.github.com/bradenm/micropy-build/micropython:v1.11-esp8266 ./esp8266

      - name: Publish Image
        run: docker push docker.pkg.github.com/bradenm/micropy-build/micropython:v1.11-esp8266
