name: Build MicroPython

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build ESP32 v1.11
        run: docker build --build-arg BRANCH="v1.11" --build-arg IDF="5c88c5996dbde6208e3bec05abc21ff6cd822d26" --tag docker.pkg.github.com/bradenm/micropy-build/micropython:v1.11-esp32 ./esp32

      - uses: actions/checkout@master
      - name: Build ESP8266 v1.11
        run: docker build --build-arg BRANCH="v1.11" --tag docker.pkg.github.com/bradenm/micropy-build/micropython:v1.11-esp8266 ./esp8266
