name: Build ESP32

on:
  push:
    branches:
      - master
    paths:
      - 'esp32/*'
      - '.github/workflows/esp32.yml'
  pull_request:
    paths:
      - 'esp32/*'
      - '.github/workflows/esp32.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [micropython]
        repo: ['https://github.com/micropython/micropython.git']
        branch: [v1.11, v1.10]
        include:
          - branch: v1.11
            idf: 5c88c5996dbde6208e3bec05abc21ff6cd822d26
          - branch: v1.10
            idf: 30545f4cccec7460634b656d278782dd7151098e

    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build ${{ matrix.name }} ESP32 ${{ matrix.branch }}
        id: micropy-build
        uses: ./actions/build-micropython
        with:
          name: ${{ matrix.name }}
          repo: ${{ matrix.repo }}
          branch: ${{ matrix.branch }}
          idf: ${{ matrix.idf }}
          path: ./esp32

      - name: Upload Binaries
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.micropy-build.outputs.binaries }}
          path: ./${{ steps.micropy-build.outputs.binaries }}
